# This rule is not used by the project argonetops itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the network.argonetops.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: argonetops
    app.kubernetes.io/managed-by: kustomize
  name: deviceconfig-editor-role
rules:
- apiGroups:
  - network.argonetops.io
  resources:
  - deviceconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - network.argonetops.io
  resources:
  - deviceconfigs/status
  verbs:
  - get
