# This rule is not used by the project argonetops itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over network.argonetops.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: argonetops
    app.kubernetes.io/managed-by: kustomize
  name: deviceconfig-admin-role
rules:
- apiGroups:
  - network.argonetops.io
  resources:
  - deviceconfigs
  verbs:
  - '*'
- apiGroups:
  - network.argonetops.io
  resources:
  - deviceconfigs/status
  verbs:
  - get
