---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - network.argonetops.io
  resources:
  - deviceconfigs
  - interfaceconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - network.argonetops.io
  resources:
  - deviceconfigs/finalizers
  - interfaceconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - network.argonetops.io
  resources:
  - deviceconfigs/status
  - interfaceconfigs/status
  verbs:
  - get
  - patch
  - update
